name: Auto Post to QuietFeed

on:
  schedule:
    - cron: "0 12 * * *"  # runs every day at 12:00 UTC
  workflow_dispatch:       # allows manual runs too

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Run auto_post.py
      run: |
        python auto_post.py

    - name: Commit and push updates
      run: |
        git config --global user.name "QuietFeed Bot"
        git config --global user.email "bot@quietfeed.com"
        git add .
        git commit -m "Auto-post update" || echo "No changes to commit"
        git push
